package com.example.currencyrates.Model

data class Rates (
    val AUD : Double = 0.0,
    val BGN : Double = 0.0,
    val BRL : Double = 0.0,
    val CAD : Double = 0.0,
    val CHF : Double = 0.0,
    val CNY : Double = 0.0,
    val CZK : Double = 0.0,
    val DKK : Double = 0.0,
    val GBP : Double = 0.0,
    val HKD : Double = 0.0,
    val HRK : Double = 0.0,
    val HUF : Double = 0.0,
    val IDR : Double = 0.0,
    val ILS : Double = 0.0,
    val INR : Double = 0.0,
    val ISK : Double = 0.0,
    val JPY : Double = 0.0,
    val KRW : Double = 0.0,
    val MXN : Double = 0.0,
    val MYR : Double = 0.0,
    val NOK : Double = 0.0,
    val NZD : Double = 0.0,
    val PHP : Double = 0.0,
    val PLN : Double = 0.0,
    val RON : Double = 0.0,
    val RUB : Double = 0.0,
    val SEK : Double = 0.0,
    val SGD : Double = 0.0,
    val THB : Double = 0.0,
    val USD : Double = 0.0,
    val ZAR : Double = 0.0
) {
    fun getDataAsMap() : Map<String, Double> {
        return mapOf<String, Double>(::AUD.name to AUD,
            ::BGN.name to BGN,
            ::BRL.name to BRL,
            ::CAD.name to CAD,
            ::CHF.name to CHF,
            ::CNY.name to CNY,
            ::CZK.name to CZK,
            ::DKK.name to DKK,
            ::GBP.name to GBP,
            ::HKD.name to HKD,
            ::HRK.name to HRK,
            ::HUF.name to HUF,
            ::IDR.name to IDR,
            ::ILS.name to ILS,
            ::INR.name to INR,
            ::ISK.name to ISK,
            ::JPY.name to JPY,
            ::KRW.name to KRW,
            ::MXN.name to MXN,
            ::MYR.name to MYR,
            ::NOK.name to NOK,
            ::NZD.name to NZD,
            ::PHP.name to PHP,
            ::PLN.name to PLN,
            ::RON.name to RON,
            ::RUB.name to RUB,
            ::SEK.name to SEK,
            ::SGD.name to SGD,
            ::THB.name to THB,
            ::USD.name to USD,
            ::ZAR.name to ZAR
        )
    }
}